{{
    config(
        materialized='table', 
        transient=false,
        database="DEV_EDW",
        schema="DBT_SRINI"
    )
}}

SELECT
    --METER.METER_NUMBER||'-'||MTR_CHAR.TIME_STAMP||'-'||MTR_CHAR.GMS_DATE as id,
	METER.METER_NUMBER,
    MTR_CHAR.TIME_STAMP,
	MTR_CHAR.CHAR_EFFECTIVE_DATE,
	MTR_CHAR.CHAR_EFFECTIVE_END_DATE,
	MTR_CHAR.SEQUENCE_NUMBER,
	MTR_CHAR.GMS_DATE,
    METER.METER_NAME,
    METER.METER_NUMBER_INDEX,
    MTR_CHAR.METER_STATUS,
    MTR_CHAR.METER_TYPE,
    CUST.COMPANY_NAME,
    CUST.COMPANY_NUMBER,
    DIR.USER_LABEL,
    DIR.BASE_DIRECTION,
    CLASS.CODE,
    CLASS.METER_CLASS,
    MTR_CHAR.PLANT,
    MTR_CHAR.AREA_ZONE,
    MTR_CHAR.DISTRICT,
    MTR_CHAR.PROJECT,
    MTR_CHAR.TECHNICIAN,
    MTR_CHAR.ANALYST,
    MTR_CHAR.COMPARE_METER,
    MTR_CHAR.ALTERNATE_METER_NUMBER,
    MTR_CHAR.POWER_PLANT,
    MTR_CHAR.OPERATOR,
    MTR_CHAR.DISCONNECT_DATE,
    MTR_CHAR.LOW_PRESS_DATE,
    MTR_CHAR.RECONNECT_DATE,
    MTR_CHAR.CONNECT_DATE,
    MTR_CHAR.INITIAL_FLOW_DATE,
    MTR_CHAR.SPLIT_CONNECT,
    MTR_CHAR.SPLIT_CONNECT_BA,
    MTR_CHAR.OUT_OF_BETA_APPROVAL,
    MTR_CHAR.DIVISION,
    MTR_CHAR.OPERATIONS_AREA,
    MTR_CHAR.ORIFICE_PLATE_DIAMETER,
    MTR_CHAR.ORIFICE_PLATE_MATERIAL,
    MTR_CHAR.TUBE_DIAMETER,
    MTR_CHAR.TUBE_MATERIAL,
    MTR_CHAR.TAP_TYPE,
    MTR_CHAR.TAP_LOCATION,
    MTR_CHAR.K_FACTOR,
    MTR_CHAR.ATMOSPHERIC_PRESSURE,
    MTR_CHAR.PRESSURE_BASE,
    MTR_CHAR.TEMPERATURE_BASE,
    METER.OPTIONAL_PRESSURE_BASE,
    METER.USER_FIELD5,
    METER.FLUID_PHASE,
    METER.CHECK_METER_EXISTS,
    METER.CONTRACT_DAY,
    METER.CONTRACT_HOUR,
    METER.COUNTRY,
    STATE.STATE,
    METER.CITY,
    IFF(LENGTH(TRIM(METER.COUNTY)) > 0, TRIM(METER.COUNTY), TRIM(COUNTY.COUNTY)) AS COUNTY,
    COUNTY.COUNTY_NAME,
    COUNTY.BASIN,
    METER2.GPS_LATITUDE,
    METER2.GPS_LONGITUDE,
    METER2.LEGAL_QUARTER,
    METER2.LEGAL_RANGE,
    METER2.LEGAL_SECTION,
    METER2.LEGAL_TOWNSHIP
FROM {{ source('dbt_enable_midstream_data_analytics', 'FC_METER') }}  METER
LEFT JOIN {{ source('dbt_enable_midstream_data_analytics', 'FC_METER_2') }}  METER2 
ON (METER.METER_NUMBER_INDEX = METER2.METER_NUMBER_INDEX)
LEFT JOIN ( SELECT sub1.* FROM (
	SELECT 
		a.METER_NUMBER_INDEX,a.METER_CLASS_INDEX,a.METER_DIRECTION_INDEX,a.METER_STATUS,a.TIME_STAMP,a.SEQUENCE_NUMBER,a.GMS_DATE,a.METER_TYPE,a.EFFECTIVE_DATE AS CHAR_EFFECTIVE_DATE,
		a.EFFECTIVE_END_DATE AS CHAR_EFFECTIVE_END_DATE,a.USER_FIELD_S01 AS PLANT,a.USER_FIELD_S02 AS AREA_ZONE,a.USER_FIELD_S03 AS DISTRICT,
		a.USER_FIELD_S04 AS PROJECT,a.USER_FIELD_S05 AS TECHNICIAN,a.USER_FIELD_S06 AS ANALYST,a.USER_FIELD_S07 AS COMPARE_METER,
		a.USER_FIELD_S08 AS ALTERNATE_METER_NUMBER,a.USER_FIELD_S09 AS POWER_PLANT,a.USER_FIELD_S10 AS OPERATOR,a.USER_FIELD_S11 AS DISCONNECT_DATE,
		a.USER_FIELD_S12 AS LOW_PRESS_DATE,a.USER_FIELD_S13 AS RECONNECT_DATE,a.USER_FIELD_S14 AS CONNECT_DATE,a.USER_FIELD_S15 AS INITIAL_FLOW_DATE,
		a.USER_FIELD_S16 AS SPLIT_CONNECT,a.USER_FIELD_S17 AS SPLIT_CONNECT_BA,a.USER_FIELD_S18 AS OUT_OF_BETA_APPROVAL,a.USER_FIELD_S20 AS DIVISION,
		a.USER_FIELD_S21 AS OPERATIONS_AREA,a.ORIFICE_PLATE_DIAMETER,a.ORIFICE_PLATE_MATERIAL,a.TUBE_DIAMETER,a.TUBE_MATERIAL,a.TAP_TYPE,
		a.TAP_LOCATION,a.K_FACTOR,a.ATMOSPHERIC_PRESSURE,a.PRESSURE_BASE,a.TEMPERATURE_BASE,
	    RANK() OVER (PARTITION BY a.METER_NUMBER_INDEX, a.TIME_STAMP ORDER BY a.SEQUENCE_NUMBER ASC) AS REVISION_IND
	FROM {{ source('dbt_enable_midstream_data_analytics', 'FC_METER_CHARACTERISTIC') }} a) sub1
	WHERE sub1.REVISION_IND = 1) MTR_CHAR
ON (METER.METER_NUMBER_INDEX = MTR_CHAR.METER_NUMBER_INDEX)
LEFT JOIN {{ source('dbt_enable_midstream_data_analytics', 'FC_METER_CLASS') }} CLASS 
ON (MTR_CHAR.METER_CLASS_INDEX = CLASS.METER_CLASS_INDEX)
LEFT JOIN {{ source('dbt_enable_midstream_data_analytics', 'FC_CUSTOMER') }} CUST 
ON (METER.CUSTOMER_INDEX = CUST.CUSTOMER_INDEX)
LEFT JOIN {{ source('dbt_enable_midstream_data_analytics', 'FC_METER_DIRECTION') }} DIR 
ON (MTR_CHAR.METER_DIRECTION_INDEX = DIR.METER_DIRECTION_INDEX)
LEFT JOIN {{ source('dbt_enable_midstream_data_analytics', 'FC_STATE') }} STATE 
ON (STATE.STATE_INDEX = METER.STATE_INDEX)
LEFT JOIN {{ source('dbt_enable_midstream_data_analytics', 'FC_COUNTY_BASIN_VW') }} COUNTY
ON (METER.COUNTY_INDEX = COUNTY.COUNTY_INDEX)